name: binary release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.4
          cache: true

      - name: Build
        uses: thatisuday/go-cross-build@v1
        with:
            ldflags: "-w -s"
            platforms: 'aix/ppc64, android/386, android/amd64, android/arm, android/arm64, darwin/amd64, darwin/arm64, dragonfly/amd64, freebsd/386, freebsd/amd64, freebsd/arm, freebsd/arm64, illumos/amd64, ios/amd64, ios/arm64, js/wasm, linux/386, linux/amd64, linux/arm, linux/arm64, linux/mips, linux/mips64, linux/mips64le, linux/mipsle, linux/ppc64, linux/ppc64le, linux/riscv64, linux/s390x, netbsd/386, netbsd/amd64, netbsd/arm, netbsd/arm64, openbsd/386, openbsd/amd64, openbsd/arm, openbsd/arm64, openbsd/mips64, plan9/386, plan9/amd64, plan9/arm, solaris/amd64, windows/386, windows/amd64, windows/arm, windows/arm64'
            name: 'wg-http-proxy'
            compress: true

      - name: Release
        uses: "ncipollo/release-action@v1.8.5"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          artifacts: "wg-http-proxy*"
          omitName: true
          tag: "latest"
          token: "${{ secrets.GITHUB_TOKEN }}"