name: build_pac_template

on: 
  workflow_dispatch: 
    inputs:
      RESOLVE_NXDOMAIN:
        description: 'Perform DNS resolving to detect and filter non-existent domains'
        required: true
        default: 'yes'
        type: choice
        options: ['yes', 'no']

concurrency:
  group: "build_pac_template"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-linux:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up tools
        run: sudo apt-get install -y sipcalc curl gawk idn python3-dnspython brotli

      - name: Generate pac
        run: bash .github/workflows/generate-pac.sh
        env:
          RESOLVE_NXDOMAIN: ${{ inputs.RESOLVE_NXDOMAIN }}
        
      - name: Make artifact
        run: tar --dereference --hard-dereference --directory ./result -cvf ${{ runner.temp }}/artifact.tar --exclude=.git --exclude=.github .

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

