name: build_pac_template

on: 
  workflow_dispatch: {}

jobs:
  build-linux:

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up tools
        run: sudo apt-get install -y sipcalc curl gawk idn python3-dnspython
     
      - name: Generate pac
        run: sudo update-alternatives --install /usr/local/bin/awk awk /usr/bin/gawk 1 && echo > ./antizapret-pac-generator-light/config/exclude-hosts-dist.txt && bash ./antizapret-pac-generator-light/doall.sh

      - name: ls
        run: ls ./antizapret-pac-generator-light/result

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 20