name: publish_release

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

jobs:
  build-linux:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
          cache: true
      
      - run: bash ./publish_release.sh

      - name: Release
        uses: "ncipollo/release-action@v1.8.5"
        with:
          allowUpdates: true
          removeArtifacts: true
          artifactErrorsFailBuild: true
          omitBody: true
          artifacts: '*${{ env.APPNAME }}*'
          omitName: true
          tag: latest
          token: "${{ secrets.GITHUB_TOKEN }}"